### PR TITLE
Extend and fix UART driver

### PR DESCRIPTION
**Pull request by LnnrtS**

### CODE REVIEW

**Comment by danngreen** [comment]
Thanks, this makes UART RX possible. The only thing I'm concerned with is that other targets (non-MP1) will not compile if they use the uart driver since `has_rx()` and `set_baudrate()` is not defined for them. Looks like that's just the F7. I can stub that out since it's outside the scope of the project you're working on.

**Comment by danngreen** [comment]
@LnnrtS Not sure if my review comment sent you a notification to you or not, but I had just one open question regarding the `__BKPT()` in `uart_target.hh`

**Comment by LnnrtS** [comment]
I didn't get a notification but I also don't see an open questions anywhere either..

**Comment by danngreen** [comment]
Weird, ok I'll paste it here:

Re: [here in uart_target](https://github.com/4ms/mdrivlib/blob/74fbcf916bc5ac96f8216a6d795d2bcb01ce2350/target/stm32mp1/drivers/uart_target.hh#L71-L75):
```
hal_h.Instance->CR2 &= ~USART_CR2_CLKEN;
if ((hal_h.Instance->CR2 & USART_CR2_CLKEN) != 0)
        __BKPT();
```

What does it mean if the CLKEN flag can't be cleared? I skimmed through the USART section of the Ref Manual but didn't see that this bit needs to be verified after clearing. Is this leftover from debugging, or should we really force a hardfault here (when no debugger is attached) because it indicates some silicon-level issue?

**Comment by LnnrtS** [comment]
This is a leftover from debugging and can be removed

**Pull request merged**
